### ISSUE TITLE
로그인 기능을 변경한다

### ISSUE THREAD

**Issue by sosow0212** [sosow0212/ChatUniv#65]
### 🔨 Describe

사용자 이탈을 방지하기 위해서 회원가입 및 로그인을 간소화합니다.

### ✅ Tasks

- [ ] 회원가입 시 username만 필요하도록 변경
- [ ] 로그인 시 계정이 없다면 회원가입 및 로그인 진행을 하고, 계정이 존재하면 로그인 시킨다
- [ ] 모든 username 반환은 `익명 + UUID` 구조로 반환해준다.
- [ ] flyway 변경
