### ISSUE TITLE
게시물 검색 기능 추가

### ISSUE THREAD

**Issue by eom-tae-in** [sosow0212/ChatUniv#74]
### 🔨 Describe

- [x] 게시물 검색 기능 추가
- [x] 쓰기와 읽기 분리
- [x] 인수테스트 작성 및 테스트 추가

### ✅ Tasks

게시물 검색 기능 추가

### 🕰️ Estimated Time of Completion

1시간
